---
title: "Viz and EDA 2"
author: "Xicheng Xie"
date: "2022-10-04"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Let's import data

```{r}
library(tidyverse)
library(ggridges)
library(patchwork)
```

```{r}
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728", "USC00519397", "USS0023B17S"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2017-01-01",
    date_max = "2017-12-31") %>%
  mutate(
    name = recode(
      id, 
      USW00094728 = "CentralPark_NY", 
      USC00519397 = "Waikiki_HA",
      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10) %>%
  select(name, id, everything())
```

## draw a scatterplot

```{r}
weather_df %>% 
  ggplot(aes(x = tmin, y = tmax)) + 
  geom_point(aes(color = name), alpha = .5) + 
  labs(
    title = "Temperature plot",
    x = "Minimum daily temperature (C)",
    y = "Maxiumum daily temperature (C)",
    caption = "Data from the rnoaa package")+
  scale_x_continuous(
    breaks=c(-10,0,15),
    labels = c("-10c","0","15"))+
  scale_color_hue(name = "Location", h = c(100, 300))
```

```{r}
ggp_weather<-weather_df %>% 
  ggplot(aes(x = tmin, y = tmax)) + 
  geom_point(aes(color = name), alpha = .5) + 
  labs(
    title = "Temperature plot",
    x = "Minimum daily temperature (C)",
    y = "Maxiumum daily temperature (C)",
    caption = "Data from the rnoaa package")+
  viridis::scale_color_viridis(
    name="location",
    discrete = TRUE
  )
```

## Themes
```{r}
ggp_weather+
  theme_bw()+
  theme(legend.position = "bottom")
```
## options set at the beginning of the code
```{r eval = FALSE}
library(tidyverse)

knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```


## data and goem()
```{r}
central_park = 
  weather_df %>% 
  filter(name == "CentralPark_NY")

waikiki = 
  weather_df %>% 
  filter(name == "Waikiki_HA")

ggplot(data = waikiki, aes(x = date, y = tmax, color = name)) + 
  geom_point() + 
  geom_line(data = central_park)
```
## Patchwork...

```{r}
tmax_tmin_plot<-
  weather_df %>% 
  ggplot(aes(x=tmin,y=tmax,color=name))+
  geom_point()+
  theme(legend.position = "bottom")

prcp_density_plot<-
  weather_df %>% 
  filter(prcp>0) %>% 
  ggplot(aes(x=prcp,fill=name))+
  geom_density(alpha=.5)+
  theme(legend.position = "bottom")

tmax_date_p = 
  weather_df %>% 
  ggplot(aes(x = date, y = tmax, color = name)) + 
  geom_point(alpha = .5) +
  geom_smooth(se = FALSE) + 
  theme(legend.position = "bottom")

(tmax_tmin_plot + prcp_density_plot) / tmax_date_p
```
## Data manipulation

```{r}
weather_df %>% 
  mutate(name=fct_reorder(name,tmax)) %>% 
  ggplot(aes(x=name,y=tmax))+
  geom_boxplot()
```
```{r}
pulse_data = 
  haven::read_sas("./data_import_examples/public_pulse_data.sas7bdat") %>%
  janitor::clean_names() %>%
  pivot_longer(
    bdi_score_bl:bdi_score_12m,
    names_to = "visit", 
    names_prefix = "bdi_score_", ###!!
    values_to = "bdi") %>%
  select(id, visit, everything()) %>% 
  mutate(visit=fct_relevel(visit,"bl"))
  
pulse_data %>% 
  ggplot(aes(x=visit,y=bdi))+
  geom_boxplot()
```





